[package]
name = "minecraft_proxy"
version = "1.0.0"
authors = ["debilausaure", "irevoire"]
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
env_logger = { version = "0.11.5", features = ["unstable-kv"] }
log = { version = "0.4.22", features = ["kv_std"] }
log-panics = "2.1.0"
mc_server_list_ping = { git = "https://github.com/debilausaure/mc_server_list_ping", branch = "cleanup" }
tokio = { version = "1.40.0", features = ["io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
